# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "Compare prompts"

prompts:
  # - "Write a tweet about {{topic}}"
  - "Write a concise, funny tweet about {{topic}}."

providers:
  - ollama:chat:phi3:mini-4k
  - ollama:chat:llama3.1
  - ollama:chat:gemma2:2b
  # - ollama:chat:mistral
  # - ollama:chat:gemma2:2b
  # - file://../gpt4o-mini.yaml

defaultTest:
  options:
    provider: file://../gpt4o-mini.yaml

tests:
  - vars:
      topic: bananas

  - vars:
      topic: avocado toast
    assert:
      # For more information on assertions, see https://promptfoo.dev/docs/configuration/expected-outputs

      # Make sure output contains the word "avocado"
      - type: icontains
        value: avocado

      # Prefer shorter outputs
      - type: javascript
        value: 1 / (output.length + 1)

  - vars:
      topic: new york city
    assert:
      # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
      - type: llm-rubric
        value: ensure that the output is funny

